# Generated by Django 4.1.4 on 2023-02-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsultarRuc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ruc_emisor", models.CharField(default="", max_length=11)),
                ("razon_social", models.CharField(default="", max_length=255)),
                (
                    "estado_cont",
                    models.CharField(
                        choices=[
                            ("00", "ACTIVO"),
                            ("01", "BAJA PROVISIONAL"),
                            ("02", "BAJA PROV. POR OFICIO"),
                            ("03", "SUSPENSION TEMPORAL"),
                            ("10", "BAJA DEFINITIVA"),
                            ("11", "BAJA DE OFICIO"),
                            ("22", "INHABILITADO-VENT.UNICA"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                    ),
                ),
                (
                    "condicion_cont",
                    models.CharField(
                        choices=[
                            ("00", "HABIDO"),
                            ("09", "PENDIENTE"),
                            ("11", "POR VERIFICAR"),
                            ("12", "NO HABIDO"),
                            ("20", "NO HALLADO"),
                        ],
                        default="HABIDO",
                        max_length=20,
                    ),
                ),
                ("domicilio", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TipoComprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_comprobante",
                    models.CharField(
                        choices=[
                            ("01", "Factura"),
                            ("02", "Boleta"),
                            ("05", "Nota de crédito"),
                        ],
                        default="Factura",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_moneda",
                    models.CharField(
                        choices=[("soles", "Soles"), ("dolares", "Dolares")],
                        default="Soles",
                        max_length=20,
                    ),
                ),
                ("serieFactura", models.CharField(max_length=50)),
                ("numeroFactura", models.CharField(max_length=50)),
                (
                    "glosa_general",
                    models.CharField(
                        choices=[
                            ("combustible", "Combustible"),
                            ("sctr", "SCTR"),
                            ("examen_medico", "EXAMEN MEDICO"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_emision", models.DateField()),
                ("ruc_emisor", models.CharField(default="", max_length=11)),
                ("ruc_receptor", models.CharField(max_length=11)),
                (
                    "glosa_especifica",
                    models.CharField(default="Glosa por defecto", max_length=255),
                ),
                (
                    "igv",
                    models.CharField(
                        choices=[("18", "18%"), ("10", "10%"), ("0", "0%")],
                        default="18%",
                        max_length=20,
                    ),
                ),
                ("sub_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("monto_igv", models.DecimalField(decimal_places=2, max_digits=10)),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
