# Generated by Django 4.1.7 on 2023-02-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura'), ('02', 'Boleta'), ('05', 'Nota de crédito')], max_length=20)),
                ('fecha_emision', models.DateField()),
                ('ruc_receptor', models.CharField(max_length=11)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
