# Generated by Django 4.1.7 on 2023-02-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocomprobante',
            name='glosa_especifica',
            field=models.CharField(default='Glosa por defecto', max_length=255),
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='ruc_emisor',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='tipo_moneda',
            field=models.CharField(choices=[('soles', 'Soles'), ('dolares', 'Dolares')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
