# Generated by Django 4.1.7 on 2023-02-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tipocomprobante_glosa_especifica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocomprobante',
            name='glosa_general',
            field=models.CharField(choices=[('combustible', 'Combustible'), ('sctr', 'SCTR'), ('examen_medico', 'EXAMEN MEDICO')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
