# Generated by Django 4.1.7 on 2023-02-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tipocomprobante_glosa_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocomprobante',
            name='numeroFactura',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='serieFactura',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
