# Generated by Django 4.1.7 on 2023-02-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tipocomprobante_numerofactura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocomprobante',
            name='igv',
            field=models.CharField(choices=[('0', '0%'), ('10', '10%'), ('18', '18%')], default=3, max_length=20),
            preserve_default=False,
        ),
    ]
