# Generated by Django 4.1.7 on 2023-02-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tipocomprobante_igv'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocomprobante',
            name='monto_igv',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
            preserve_default=False,
        ),
    ]
