# Generated by Django 4.1.7 on 2023-02-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tipocomprobante_monto_igv_tipocomprobante_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocomprobante',
            name='igv',
            field=models.CharField(choices=[('0', '0%'), ('10', '10%'), ('18', '18%')], default='18%', max_length=20),
        ),
    ]
