# Generated by Django 4.1.7 on 2023-02-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_tipocomprobante_igv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocomprobante',
            name='tipo_comprobante',
            field=models.CharField(choices=[('01', 'Factura'), ('02', 'Boleta'), ('05', 'Nota de crédito')], default='Factura', max_length=20),
        ),
        migrations.AlterField(
            model_name='tipocomprobante',
            name='tipo_moneda',
            field=models.CharField(choices=[('soles', 'Soles'), ('dolares', 'Dolares')], default='Soles', max_length=20),
        ),
    ]
