# Generated by Django 4.1.7 on 2023-02-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_tipocomprobante_tipo_comprobante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultarRuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc_emisor', models.CharField(default='', max_length=11)),
                ('razon_social', models.CharField(default='', max_length=255)),
                ('estado_cont', models.CharField(choices=[('00', 'ACTIVO'), ('01', 'BAJA PROVISIONAL'), ('02', 'BAJA PROV. POR OFICIO'), ('03', 'SUSPENSION TEMPORAL'), ('10', 'BAJA DEFINITIVA'), ('11', 'BAJA DE OFICIO'), ('22', 'INHABILITADO-VENT.UNICA')], default='ACTIVO', max_length=20)),
                ('condicion_cont', models.CharField(choices=[('00', 'HABIDO'), ('09', 'PENDIENTE'), ('11', 'POR VERIFICAR'), ('12', 'NO HABIDO'), ('20', 'NO HALLADO')], default='HABIDO', max_length=20)),
                ('domicilio', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
