CREATE TABLE CLIENTE 
(
  ID_CLIENTE NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL 
, NOMBRE VARCHAR2(50) NOT NULL 
, APELLIDO VARCHAR2(50) NOT NULL 
, DIRECCION VARCHAR2(50) NOT NULL 
, FECHA_NACIMIENTO DATE NOT NULL 
, TELEFONO NUMBER NOT NULL 
, EMAIL VARCHAR2(20) NOT NULL 
, CONSTRAINT CLIENTE_PK PRIMARY KEY 
  (
    ID_CLIENTE 
  )
  ENABLE 
);

CREATE TABLE MODO_PAGO
(
  NUM_PAGO NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL  
, NOMBRE VARCHAR2(50) NOT NULL  
, CONSTRAINT MODO_PAGO_PK PRIMARY KEY 
  (
    NUM_PAGO 
  )
  ENABLE 
);

CREATE TABLE  FACTURA
(
  NUM_FACTURA NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL 
, ID_CLIENTE NUMBER NOT NULL 
, FECHA DATE NOT NULL 
, NUM_PAGO NUMBER NOT NULL 
 
, CONSTRAINT FACTURA_FK1 
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE)
,CONSTRAINT FACTURA_FK2
    FOREIGN KEY (NUM_PAGO)
    REFERENCES MODO_PAGO(NUM_PAGO)
, CONSTRAINT FACTURA_PK PRIMARY KEY 
  (
    NUM_FACTURA 
  )
  ENABLE
)
;

CREATE TABLE PRODUCTO
(
  ID_PRODUCTO NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL 
, NOMBRE VARCHAR2(50) NOT NULL
, PRECIO VARCHAR2(50) NOT NULL 
, STOK VARCHAR2(50) NOT NULL 
, ID_CATEGORIA NUMBER NOT NULL 

, CONSTRAINT PRODUCTO_PK PRIMARY KEY 
  (
    ID_PRODUCTO 
  )
  ENABLE 
);
CREATE TABLE CATEGORIA 
(
  ID_CATEGORIA NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL 
, NOMBRE VARCHAR2(50) 
, DESCRIPCION VARCHAR2(20) 
, CONSTRAINT CATEGORIA_PK PRIMARY KEY 
  (
    ID_CATEGORIA 
  )
  ENABLE 
);

CREATE TABLE  DETALLE
(
  NUM_DETALLE NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL  
, ID_FACTURA NUMBER NOT NULL 
, ID_PRODUCTO NUMBER NOT NULL  
, CANTIDAD VARCHAR2(50) NOT NULL 
, PRECIO VARCHAR2(50) NOT NULL
, CONSTRAINT DETALLE_FK1 
    FOREIGN KEY (ID_FACTURA)
    REFERENCES FACTURA(NUM_FACTURA)
,CONSTRAINT DETALLE_FK2
    FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO(ID_PRODUCTO)
, CONSTRAINT DETALLE_PK PRIMARY KEY 
  (
    NUM_DETALLE 
  )
  ENABLE
)
;
SELECT * FROM DETALLE
INSERT INTO MODO_PAGO(NOMBRE) VALUES('PAYPAL');
INSERT INTO MODO_PAGO(NOMBRE) VALUES('SKRILL');
INSERT INTO CATEGORIA(NOMBRE,DESCRIPCION) VALUES('Lenta','Comida de Alto Valor');
INSERT INTO CLIENTE(NOMBRE,APELLIDO,DIRECCION,FECHA_NACIMIENTO,TELEFONO,EMAIL) VALUES('DANILO','PEREZ','BARRIO SANTOD',TO_DATE('02/04/2000', 'DD/MM/YYYY'),31235,'daniulo@gmail.com');
INSERT INTO PRODUCTO(NOMBRE,PRECIO,STOK,ID_CATEGORIA) VALUES('HAMBURGUESA','20','10U',1);
INSERT INTO FACTURA VALUES(1,1,TO_DATE('1994/12/16 12:00:00', 'yyyy/mm/dd hh:mi:ss'),1);
DROP TABLE CATEGORIAS
CREATE OR REPLACE PROCEDURE SP_INSERT_CATEGORIA(
P_NOMBRE IN CATEGORIA.NOMBRE%TYPE,
P_DESCRIPCION IN CATEGORIA.DESCRIPCION%TYPE,
P_RESULT OUT VARCHAR2
)
AS
 BEGIN
    INSERT INTO CATEGORIA(NOMBRE,DESCRIPCION) VALUES(P_NOMBRE,P_DESCRIPCION);
    P_RESULT := 'SE EJECUTO CORREDCTAMENTE';
    COMMIT;
    EXCEPTION
     WHEN OTHERS THEN
            P_RESULT := 'ERROR AL INSERTAR';
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE SP_UPDATE_CATEGORIA(
P_ID_CATEGORIA IN CATEGORIA.ID_CATEGORIA%TYPE,
P_NOMBRE IN CATEGORIA.NOMBRE%TYPE,
P_DESCRIPCION IN CATEGORIA.DESCRIPCION%TYPE,
P_RESULT OUT VARCHAR2
)
AS
 BEGIN
    UPDATE CATEGORIA SET NOMBRE = P_NOMBRE , DESCRIPCION = P_DESCRIPCION WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    P_RESULT := 'SE EJECUTO CORREDCTAMENTE';
    COMMIT;
    EXCEPTION
     WHEN OTHERS THEN
            P_RESULT := 'ERROR AL ACTUALIZAR';
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE SP_DELETE_CATEGORIA(
P_ID_CATEGORIA IN CATEGORIA.ID_CATEGORIA%TYPE,
P_RESULT OUT VARCHAR2
)
AS
 BEGIN
    DELETE FROM CATEGORIA  WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    P_RESULT := 'SE EJECUTO CORREDCTAMENTE';
    COMMIT;
    EXCEPTION
     WHEN OTHERS THEN
            P_RESULT := 'ERROR AL ELIMINAR';
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE SP_SELECT_CATEGORIA(
P_CURSOR OUT SYS_REFCURSOR 
)
AS
 BEGIN
 OPEN P_CURSOR FOR
  SELECT  * FROM CATEGORIA;


END;


CREATE OR REPLACE PROCEDURE SP_INSERT_FACTURA(

P_ID_CLIENTE IN FACTURA.ID_CLIENTE%TYPE,
P_FECHA IN FACTURA.FECHA%TYPE,
P_NUM_PAGO IN FACTURA.NUM_PAGO%TYPE,
P_RESULT OUT VARCHAR2
)
AS
 BEGIN
    INSERT INTO FACTURA(ID_CLIENTE,FECHA,NUM_PAGO) VALUES(P_ID_CLIENTE,P_FECHA,P_NUM_PAGO);
    P_RESULT := 'SE EJECUTO CORREDCTAMENTE';
    COMMIT;
    EXCEPTION
     WHEN OTHERS THEN
            P_RESULT := 'ERROR AL INSERTAR';
            ROLLBACK;
END;
CREATE OR REPLACE PROCEDURE SP_INSERT_DETALLE(

P_ID_FACTURA IN DETALLE.ID_FACTURA%TYPE,
P_ID_PRODUCTO IN DETALLE.ID_PRODUCTO%TYPE,
P_CANTIDAD IN DETALLE.CANTIDAD%TYPE,
P_PRECIO IN DETALLE.PRECIO%TYPE,
P_RESULT OUT VARCHAR2
)
AS
 BEGIN
    INSERT INTO FACTURA(ID_CLIENTE,FECHA,NUM_PAGO) VALUES(P_ID_CLIENTE,P_FECHA,P_NUM_PAGO);
    P_RESULT := 'SE EJECUTO CORREDCTAMENTE';
    COMMIT;
    EXCEPTION
     WHEN OTHERS THEN
            P_RESULT := 'ERROR AL INSERTAR';
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE SP_UPDATE_FACTURA(
P_NUM_FACTURA IN FACTURA.NUM_FACTURA%TYPE,
P_ID_CLIENTE IN FACTURA.ID_CLIENTE%TYPE,
P_FECHA IN FACTURA.FECHA%TYPE,
P_NUM_PAGO IN FACTURA.NUM_PAGO%TYPE,
P_RESULT OUT VARCHAR2
)
AS
 BEGIN
    UPDATE FACTURA SET NUM_FACTURA = P_NUM_FACTURA , ID_CLIENTE = P_ID_CLIENTE, FECHA = P_FECHA, NUM_PAGO = P_NUM_PAGO  WHERE NUM_FACTURA = P_NUM_FACTURA;
    P_RESULT := 'SE EJECUTO CORREDCTAMENTE';
    COMMIT;
    EXCEPTION
     WHEN OTHERS THEN
            P_RESULT := 'ERROR AL ACTUALIZAR';
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE SP_DELETE_FACTURA(
P_NUM_FACTURA IN FACTURA.NUM_FACTURA%TYPE,
P_RESULT OUT VARCHAR2
)
AS
 BEGIN
    DELETE FROM FACTURA  WHERE NUM_FACTURA = P_NUM_FACTURA;
    P_RESULT := 'SE EJECUTO CORREDCTAMENTE';
    COMMIT;
    EXCEPTION
     WHEN OTHERS THEN
            P_RESULT := 'ERROR AL ELIMINAR';
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE SP_SELECT_FACTURA(
P_CURSOR OUT SYS_REFCURSOR 
)
AS
 BEGIN
 OPEN P_CURSOR FOR
  SELECT  * FROM FACTURA;


END;



CREATE OR REPLACE PROCEDURE SP_INSERT_MODOPAGO(
P_NOMBRE IN MODO_PAGO.NOMBRE%TYPE,
P_RESULT OUT VARCHAR2
)
AS
 BEGIN
    INSERT INTO MODO_PAGO(NOMBRE) VALUES(P_NOMBRE);
    P_RESULT := 'SE EJECUTO CORREDCTAMENTE';
    COMMIT;
    EXCEPTION
     WHEN OTHERS THEN
            P_RESULT := 'ERROR AL INSERTAR';
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE SP_UPDATE_MODOPAGO(
P_NUM_PAGO IN MODO_PAGO.NUM_PAGO%TYPE,
P_NOMBRE IN MODO_PAGO.NOMBRE%TYPE,
P_RESULT OUT VARCHAR2
)
AS
 BEGIN
    UPDATE MODO_PAGO SET NOMBRE = P_NOMBRE  WHERE NUM_PAGO = P_NUM_PAGO;
    P_RESULT := 'SE EJECUTO CORREDCTAMENTE';
    COMMIT;
    EXCEPTION
     WHEN OTHERS THEN
            P_RESULT := 'ERROR AL ACTUALIZAR';
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE SP_DELETE_MODOPAGO(
P_NUM_PAGO IN MODO_PAGO.NUM_PAGO%TYPE,
P_RESULT OUT VARCHAR2
)
AS
 BEGIN
    DELETE FROM MODO_PAGO  WHERE NUM_PAGO = P_NUM_PAGO;
    P_RESULT := 'SE EJECUTO CORREDCTAMENTE';
    COMMIT;
    EXCEPTION
     WHEN OTHERS THEN
            P_RESULT := 'ERROR AL ELIMINAR';
            ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE SP_SELECT_MODOPAGO(
P_CURSOR OUT SYS_REFCURSOR 
)
AS
 BEGIN
 OPEN P_CURSOR FOR
  SELECT  NUM_PAGO,NOMBRE FROM MODO_PAGO;


END;

CREATE OR REPLACE PROCEDURE SP_CREANDOFACTURA(

P_NUM_PAGO IN FACTURA.NUM_PAGO%TYPE,
P_ID_PRODUCTO IN DETALLE.ID_PRODUCTO%TYPE,
P_CANTIDAD IN DETALLE.CANTIDAD%TYPE,
P_PRECIO IN DETALLE.PRECIO%TYPE,
P_RESULT OUT VARCHAR2
)
AS
 BEGIN
    INSERT INTO FACTURA(ID_CLIENTE,FECHA,NUM_PAGO) VALUES(1,SYSDATE,P_NUM_PAGO);
    INSERT INTO DETALLE(ID_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES((SELECT NUM_FACTURA FROM FACTURA WHERE NUM_FACTURA in (select max(NUM_FACTURA) from FACTURA)),P_ID_PRODUCTO,P_CANTIDAD, P_PRECIO);
    P_RESULT := 'SE EJECUTO CORREDCTAMENTE'; 
    COMMIT;
    EXCEPTION
     WHEN OTHERS THEN
            P_RESULT := 'ERROR AL INSERTAR';
            ROLLBACK;
END;

